### ISSUE TITLE
Getting strange Flame graph 

### ISSUE THREAD

**Issue by MikhailZhyhariev** [nvdv/vprof#88] opened 2018-11-03 20:28 UTC
##### Description
Getting strange Flame graph. You can see it in the image :) 
<img width="1440" alt="2018-11-03 22 25 20" src="https://user-images.githubusercontent.com/30877238/47957041-b72d2b00-dfb7-11e8-8a7d-2019a38335f9.png">

**Comment by nvdv** [comment] 2018-11-10 09:53
Do you use Safari?
If so - then it's duplicate of #74

**Closed** 2018-11-29 17:38 UTC
Labels: duplicate
