### ISSUE TITLE
module 'signal' has no attribute 'SIGPROF'

### ISSUE THREAD

**Issue by AronWater** [nvdv/vprof#104] opened 2020-06-11 19:06 UTC
##### How to reproduce
`vprof -c cmh permutations.py`
##### Actual results
`ermutations.py
Running MemoryProfiler...
[('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('A', 'F'), ('A', 'G'), ('A', 'E'), ('A', 'D'), ('B', 'A'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('B', 'F'), ('B', 'G'), ('B', 'E'), ('B', 'D'), ('C', 'A'), ('C', 'B'), ('C', 'D'), ('C', 'E'), ('C', 'F'), ('C', 'G'), ('C', 'E'), ('C', 'D'), ('D', 'A'), ('D', 'B'), ('D', 'C'), ('D', 'E'), ('D', 'F'), ('D', 'G'), ('D', 'E'), ('D', 'D'), ('E', 'A'), ('E', 'B'), ('E', 'C'), ('E', 'D'), ('E', 'F'), ('E', 'G'), ('E', 'E'), ('E', 'D'), ('F', 'A'), ('F', 'B'), ('F', 'C'), ('F', 'D'), ('F', 'E'), ('F', 'G'), ('F', 'E'), ('F', 'D'), ('G', 'A'), ('G', 'B'), ('G', 'C'), ('G', 'D'), ('G', 'E'), ('G', 'F'), ('G', 'E'), ('G', 'D'), ('E', 'A'), ('E', 'B'), ('E', 'C'), ('E', 'D'), ('E', 'E'), ('E', 'F'), ('E', 'G'), ('E', 'D'), ('D', 'A'), ('D', 'B'), ('D', 'C'), ('D', 'D'), ('D', 'E'), ('D', 'F'), ('D', 'G'), ('D', 'E')]
Running FlameGraphProfiler...
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\vprof.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\vprof\__main__.py", line 83, in main
    program_stats = runner.run_profilers(source, config, verbose=True)
  File "c:\programdata\anaconda3\lib\site-packages\vprof\runner.py", line 73, in run_profilers
    run_stats[option] = curr_profiler.run()
  File "c:\programdata\anaconda3\lib\site-packages\vprof\base_profiler.py", line 172, in run
    return self.profile()
  File "c:\programdata\anaconda3\lib\site-packages\vprof\flame_graph.py", line 167, in profile_module
    return base_profiler.run_in_separate_process(self._profile_module)
  File "c:\programdata\anaconda3\lib\site-packages\vprof\base_profiler.py", line 79, in run_in_separate_process
    raise exc
AttributeError: module 'signal' has no attribute 'SIGPROF`

##### Version and platform
window10

**Comment by bilderbuchi** [comment] 2020-11-06 10:29
I believe this is a duplicate of #62.

**Comment by nvdv** [comment] 2020-11-07 07:58
Yeah, thanks

**Closed** 2020-11-07 07:58 UTC
Labels: duplicate
